name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Android release
        run: flutter build appbundle
