name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--

      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter doctor -v
      - run: flutter pub get

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Android release
        run: flutter build appbundle
