name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Android release
        run: flutter build appbundle

      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-app-release
          path: build/app/outputs/bundle/release/*.aab

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
        working-directory: ./ios

      - name: Build iOS release
        run: flutter build ipa --release

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-app-release
          path: build/ios/ipa/*.ipa
